# Use the official Python image
FROM python:3.9-slim
# Set environment variables
ENV PYTHONUNBUFFERED 1
# Create and set the working directory
WORKDIR /app
# Install dependencies
COPY ./requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
# Copy the rest of the application
COPY . /app/
# Expose port for Django
EXPOSE 8000
# Run Django server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
