version: '3.8'
services:
  backend:
    build:
      context: ./django_backend
      dockerfile: dockerfile  # Dockerfile for Django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./django_backend:/app
    environment:
      - DEBUG=True

  frontend:
    build:
      context: ./myapp  # Path to React app folder
      dockerfile: dockerfile  # Dockerfile for React
    ports:
      - "3000:3000"
    stdin_open: true  # Keep the container running for development
    volumes:
      - ./myapp:/app
      - /myapp/node_modules
    command: npm start
